### PR TITLE
(maint) always run tests with schema validation

### PR DESCRIPTION
**Pull request by wkalt**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
You'll want to update the Travis config as well; this changed doubled the time because it's running everything twice.

**Comment by wkalt** [comment]
@MikaelSmith I updated travis.yaml. The test failures seem unrelated but probably warrant some investigation.

**Comment by MikaelSmith** [comment]
Oh, there's a good reason to test without schema validation. Previously we had relied on schemas to catch errors, and our tests started failing when we switched schema validation off by default. So we started testing both.

**Comment by wkalt** [comment]
@MichaelSmith this will test both on travis now

**Comment by wkalt** [comment]
@MikaelSmith rather

**Comment by MikaelSmith** [comment]
@mruzicka do you have any thoughts on this?

**Comment by mruzicka** [comment]
@MikaelSmith @wkalt I'd prefer running the tests with the schema checks on only. The reason we gave up on that was that the tests were occasionally failing due to timeouts.

**Comment by MikaelSmith** [comment]
We run tests in CI with schema checks both enabled and disabled. Each can potentially catch issues.

This would be inconsistent with some other projects, and I don't see a strong use case for it (it's easy to run locally if CI failed).

**Pull request closed without merging**
