### PR TITLE
(packaging) Prepare 1.3.0

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This test has been unstable in CI recently, worth looking deeper.

**Comment by MikaelSmith** [comment]
Travis CI failure filed as [PCP-735](https://tickets.puppetlabs.com/browse/PCP-735) to deal with later.

**Comment by MikaelSmith** [comment]
This should hold off until we fix the tk-metrics 1.0 issue.

**Comment by MikaelSmith** [comment]
@rlinehan this should be ready now

**Comment by rlinehan** [comment]
Travis failure due to PCP-735, I reran.

**Pull request merged**
