### PR TITLE
Prepare 1.0.0

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Updated.

**Comment by MikaelSmith** [comment]
@puppetlabs/pcp-broker-maintainers planning a 1.0.0 release. I think (almost) everything else planned can be done additively in major releases.

**Comment by wkalt** [comment]
hold off on this for the time being. I'm looking into a possible issue.

**Comment by wkalt** [comment]
Resolved my issue. It wasn't a problem with this code, so this is good to go afaik.

**Comment by MikaelSmith** [comment]
Should be ready to go.

**Comment by mruzicka** [comment]
👍

**Pull request merged**
